### ISSUE TITLE
Shared subscription load balancing strategies?

### ISSUE THREAD

**Issue by 414owen** [halfgaar/FlashMQ#28]
Hi,
FlashMQ seems like a fantastic broker :)
I was wondering if load balancing strategies have been considered for FlashMQ.
Specifically, I'm interested in emqx's ['hash'](https://www.emqx.io/docs/en/v5.0/advanced/shared-subscriptions.html#load-balancing-policy-and-dispatch-ack-configuration) strategy, which effectively pairs publishers with subscribers.

**Comment by halfgaar** [comment]
Absolutely. It's on the list. I'll keep you updated with this issue.

**Comment by halfgaar** [comment]
I pushed a branch with a beta version of shared subscriptions: https://github.com/halfgaar/FlashMQ/tree/shared-subscriptions-beta

I can provide a build for you if you want, if it's an Ubuntu / Debian version on x64, or the x64 AppImage.

I would like to know more about how you see the hash strategy working. Currently, the man page says:

> `sender_hash`. Selects a receiver deterministically based on the hash of the client ID of the sender. The selected subscriber will depend on how many subscribers there are, so if some disconnect, the distribution will change. Moreover, the selection may also change when FlashMQ cleans up empty spaces in the list of shared subscribers.

Pairing subscribers to publishers predictably/consistently is hard this way, because a receiver has to be selected, and if subscribers disappear, this changes result.

**Comment by halfgaar** [comment]
Included in FlashMQ 1.2.0.
